import type { Metadata } from "next";
import { LeadForm } from "@/components/LeadForm";
import { site } from "@/lib/content";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata("Contact", "Contact Top Design for free website audit, SEO consultation, instant quote, callback request, WhatsApp chat, and meeting scheduling.", "/contact");

export default function ContactPage() {
  return <main><section className="bg-ink py-20 text-white"><div className="container-pad grid gap-10 lg:grid-cols-[1fr_460px]"><div><p className="section-kicker !border-white/20 !bg-white/10 !text-cyan">Contact</p><h1 className="text-5xl font-black md:text-7xl">Start with a free audit, quote, or growth strategy call.</h1><p className="mt-6 text-white/70">Use the form for website development, mobile app development, digital marketing, SEO, interiors, printing, branding, or business management solutions.</p><div className="mt-8 flex flex-wrap gap-3"><a href={site.whatsapp} className="rounded-full bg-emerald-500 px-6 py-4 font-black text-white">WhatsApp chat</a><a href={`tel:${site.phone}`} className="rounded-full border border-white/25 px-6 py-4 font-black">Call button</a><a href={`mailto:${site.email}`} className="rounded-full border border-white/25 px-6 py-4 font-black">Email us</a></div></div><LeadForm /></div></section><section className="py-16"><div className="container-pad grid gap-6 md:grid-cols-3"><div id="audit" className="rounded-4xl border border-slate-200 p-6"><h2 className="text-2xl font-black">Free Website Audit</h2><p className="mt-3 text-slate-600">Performance, SEO, UX, tracking, and conversion review.</p></div><div id="quote" className="rounded-4xl border border-slate-200 p-6"><h2 className="text-2xl font-black">Get Instant Quote</h2><p className="mt-3 text-slate-600">Share budget, city, service, and requirements for a clear estimate.</p></div><div id="meeting" className="rounded-4xl border border-slate-200 p-6"><h2 className="text-2xl font-black">Schedule Meeting</h2><p className="mt-3 text-slate-600">Book a discovery call, site visit, or strategy session.</p></div></div></section><section className="bg-frost py-16"><div className="container-pad"><div className="grid min-h-80 place-items-center rounded-4xl border border-slate-200 bg-white p-8 text-center shadow-card"><div><h2 className="text-3xl font-black">Google Maps embed</h2><p className="mt-3 text-slate-600">Replace this production placeholder with the Google Maps embed URL and verified business profile location.</p></div></div></div></section></main>;
}
