import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata("Admin Dashboard", "Secure JWT admin dashboard blueprint for lead, CMS, blog, portfolio, service, testimonial, SEO, and analytics management.", "/admin");

const modules = ["Lead management", "CMS pages", "Blog management", "Portfolio management", "Service management", "Testimonials", "SEO settings", "Analytics dashboard", "Email & WhatsApp notifications"];
const leadFields = ["Name", "Company", "Phone", "Email", "Service", "Budget", "City", "Project Details", "Preferred Contact Method"];

export default function AdminPage() {
  return <main><section className="bg-ink py-20 text-white"><div className="container-pad"><p className="section-kicker !border-white/20 !bg-white/10 !text-cyan">Admin</p><h1 className="max-w-4xl text-5xl font-black md:text-7xl">JWT-secured dashboard for teams that convert enquiries into revenue.</h1><div className="mt-8 grid max-w-md gap-3 rounded-4xl bg-white p-5 text-ink"><input placeholder="Email" className="rounded-2xl border border-slate-200 px-4 py-3"/><input placeholder="Password" type="password" className="rounded-2xl border border-slate-200 px-4 py-3"/><button className="rounded-2xl bg-royal px-4 py-3 font-black text-white">Secure Login</button></div></div></section><section className="py-16"><div className="container-pad grid gap-6 lg:grid-cols-[1fr_380px]"><div className="rounded-4xl border border-slate-200 p-6 shadow-card"><h2 className="text-3xl font-black">Lead pipeline</h2><div className="mt-6 grid gap-3 md:grid-cols-4">{["New", "Contacted", "Proposal", "Won"].map((stage) => <div key={stage} className="min-h-40 rounded-3xl bg-frost p-4"><h3 className="font-black">{stage}</h3><p className="mt-2 text-sm text-slate-600">Search, filter, assign, status tracking, notes, follow-ups.</p></div>)}</div><h3 className="mt-8 font-black">Lead fields</h3><div className="mt-3 flex flex-wrap gap-2">{leadFields.map((field) => <span key={field} className="rounded-full bg-frost px-3 py-2 text-sm font-bold">{field}</span>)}</div></div><aside className="rounded-4xl bg-ink p-6 text-white"><h2 className="text-2xl font-black">RBAC modules</h2><div className="mt-5 grid gap-3">{modules.map((module) => <div key={module} className="rounded-2xl bg-white/10 p-3 font-bold">{module}</div>)}</div></aside></div></section></main>;
}
