import type { Metadata } from "next";
import { blogPosts } from "@/lib/content";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata("Blog", "SEO-friendly Top Design blog with categories, tags, search, related posts, and social sharing topics.", "/blog");

export default function BlogPage() {
  const categories = Array.from(new Set(blogPosts.map((post) => post.category)));
  return <main><section className="bg-ink py-20 text-white"><div className="container-pad"><p className="section-kicker !border-white/20 !bg-white/10 !text-cyan">Blog</p><h1 className="max-w-4xl text-5xl font-black md:text-7xl">Guides for websites, SEO, branding, interiors, marketing, and business growth.</h1><div className="mt-8 max-w-2xl rounded-full bg-white p-2"><input aria-label="Search blog" placeholder="Search guides, tags, and categories" className="w-full rounded-full px-5 py-3 text-ink focus:outline-none" /></div></div></section><section className="py-16"><div className="container-pad grid gap-8 lg:grid-cols-[260px_1fr]"><aside className="rounded-4xl bg-frost p-6"><h2 className="font-black">Categories</h2><div className="mt-4 grid gap-2">{categories.map((cat) => <button key={cat} className="rounded-full bg-white px-4 py-2 text-left font-bold">{cat}</button>)}</div><h2 className="mt-8 font-black">Popular tags</h2><div className="mt-4 flex flex-wrap gap-2">{Array.from(new Set(blogPosts.flatMap((post) => post.tags))).map((tag) => <span key={tag} className="rounded-full border border-slate-200 px-3 py-1 text-sm">#{tag}</span>)}</div></aside><div className="grid gap-6 md:grid-cols-2">{blogPosts.map((post) => <article key={post.slug} className="card-hover rounded-4xl border border-slate-200 p-6 shadow-card"><span className="text-sm font-black text-royal">{post.category}</span><h2 className="mt-3 text-2xl font-black">{post.title}</h2><p className="mt-4 text-slate-600">SEO-friendly URL: /blog/{post.slug}</p><div className="mt-5 flex flex-wrap gap-2">{post.tags.map((tag) => <span key={tag} className="rounded-full bg-frost px-3 py-1 text-sm">{tag}</span>)}</div><div className="mt-6 flex gap-3 text-sm font-black text-royal"><button>Share</button><button>Related posts</button></div></article>)}</div></div></section></main>;
}
