import type { Metadata } from "next";
import { ContactCTA } from "@/components/CTA";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata("About Us", "Learn about Top Design company story, mission, vision, team, certifications, and achievements.", "/about");

export default function AboutPage() {
  return <main><section className="bg-frost py-20"><div className="container-pad"><p className="section-kicker">About Top Design</p><h1 className="section-title max-w-4xl">A premium creative, technology, and business growth partner for ambitious local brands.</h1><p className="mt-6 max-w-3xl text-lg text-slate-600">Top Design was built to remove the gap between attractive design and measurable business outcomes. Our teams combine digital strategy, product development, marketing, interiors, print production, and management systems.</p></div></section><section className="py-16"><div className="container-pad grid gap-6 md:grid-cols-3"><div className="rounded-4xl bg-ink p-8 text-white"><h2 className="text-2xl font-black">Mission</h2><p className="mt-4 text-white/70">Help startups and local businesses look premium, generate qualified leads, and manage growth with reliable systems.</p></div><div className="rounded-4xl bg-royal p-8 text-white"><h2 className="text-2xl font-black">Vision</h2><p className="mt-4 text-white/80">Become the most trusted integrated design and growth partner for businesses moving from offline to omnichannel.</p></div><div className="rounded-4xl bg-frost p-8"><h2 className="text-2xl font-black">Certifications</h2><p className="mt-4 text-slate-600">Google Analytics, Search Console, Meta Ads, accessibility, security, and performance-first delivery standards.</p></div></div></section><section className="bg-ink py-16 text-white"><div className="container-pad"><h2 className="text-4xl font-black">Team pods</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{["Strategists", "UX/UI Designers", "Developers", "Marketing Specialists"].map((role) => <div key={role} className="rounded-3xl border border-white/10 bg-white/5 p-6 font-black">{role}</div>)}</div></div></section><ContactCTA /></main>;
}
